<?xml version="1.0"?>
<package format="3">
  <name>advanced_localization_cpp</name>
  <version>0.1.0</version>
  <description>C++ ROS 2 PX4 uXRCE-DDS GPS-denied localization node for Orin Nano.</description>
  <maintainer email="maintainer@example.com">advanced_localization</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>px4_msgs</depend>
  <depend>eigen</depend>
  <depend>opencv</depend>
  <depend>yaml-cpp</depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
